import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const stylesDir = join(root, "src", "styles")
const outDir = join(root, "src", "generated")

const files = ["mdx-prose.css", "mdx-ui.css"]

let combined = ""
for (const file of files) {
  combined += readFileSync(join(stylesDir, file), "utf8") + "\n"
}

mkdirSync(outDir, { recursive: true })
writeFileSync(
  join(outDir, "mdx-inline-styles.ts"),
  `/** Generated by scripts/inline-styles.mjs — do not edit */\nexport const mdxInlineStyles = ${JSON.stringify(combined)} as string\n`
)

console.log("Wrote src/generated/mdx-inline-styles.ts")
