export { MdxReading, type MdxReadingProps } from "./mdx/mdx-reading"
export { mdxComponents, PageHeader } from "./mdx/mdx-components"
export { TocLayout } from "./components/toc"
export { mdxTocLayoutVars } from "./lib/toc-vars"
export { extractHeadings, type TocItem } from "./lib/heading-slug"
export { mdxTableComponents } from "./components/table"
export type { ShikiTheme } from "./lib/shiki"
